service: tezos-estimator
frameworkVersion: "3"
useDotenv: true

custom:
  serverlessSsmFetch:
    TEZOS_ESTIMATOR: TEZOS_ESTIMATOR

provider:
  name: aws
  runtime: nodejs16.x
  profile: serverless-estimator
  environment:
    TEZOS_ESTIMATOR: ${env:TEZOS_ESTIMATOR}

functions:
  getContractMethods:
    handler: handler.getContractMethods
    events:
      - httpApi:
          path: /contractMethods
          method: post
  estimateGas:
    handler: handler.estimateGasForMethod
    events:
      - httpApi:
          path: /estimateGas
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
